project:
  type: website
  output-dir: docs
  resources:
  #   - hw-solutions
    - data
  render:
  - "*.qmd"
  - "!/teaching-materials"
  - "!/quizzes"
website:
  title: "STA221"
  search: true
  navbar:
    background: "#2774AE"
    # background: "#012169"
    foreground: "#FFFFFF"
    left:
      - href: index.qmd
        text: schedule
      - href: syllabus.qmd
        text: syllabus
      - href: project.qmd
        text: project
      - text: "homeworks"
        menu:
          - href: hw/hw01.qmd
            text: "hw 1"
          - href: hw/hw02.qmd
            text: "hw 2"
          - href: hw/hw03.qmd
            text: "hw 3"
          - href: hw/hw04.qmd
            text: "hw 4"
      - text: "labs"
        menu:
          - href: labs/lab00.qmd
            text: "lab 0"
          - href: labs/lab01.qmd
            text: "lab 1"
          - href: labs/lab02.qmd
            text: "lab 2"
          - href: labs/lab03.qmd
            text: "lab 3"
          - href: labs/lab04.qmd
            text: "lab 4"
          - href: labs/lab05.qmd
            text: "lab 5"
          - href: labs/lab06.qmd
            text: "lab 6"
          - href: labs/lab07.qmd
            text: "lab 7"
            # - href: notes/exam-notes.qmd
      #   text: distributions
      # - href: chapterSummaries.qmd
      #   text: notes
      - href: links.qmd
        text: links
      

format:
  html:
    theme: cosmo
    mainfont: Lato
    css: styles.css
    toc: true


